import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

import NextTopLoader from "nextjs-toploader";
import { getUser, verify } from "@/lib/utils";
import UserContextWrapper from "@/components/UserContextWrapper";
import { cookies } from "next/headers";
import { prisma } from "@/db";
import { User } from "@prisma/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCurrentUser() {
  const token = cookies().get("token");

  const user = token?.value ? ((await verify(token?.value)) as User) : null;

  const fromDb = await prisma.user.findFirst({
    where: {
      email: user?.email,
    },
  });
  return fromDb;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: "#cfd7e6",
          margin: "0",
          padding: "0",
          overflowX: "hidden",
        }}
        className={inter.className}
      >
        <NextTopLoader />
        <UserContextWrapper user={user}>{children}</UserContextWrapper>
        <Toaster />
      </body>
    </html>
  );
}
