import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: "#cfd7e6",
          margin: "0",
          padding: "0",
          overflowX: "hidden",
        }}
        className={inter.className}
      >
        <NextTopLoader />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
